server:
  address: 0.0.0.0
  port: 8888

spring:
  profiles:
    active: test,native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
