server:
  port: 8081

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: productos
          uri: http://localhost:8090
          predicates:             
            - Path=/api/v1/productos/**
        - id: pedidos
          uri: http://localhost:9090
          predicates:
            - Path=/api/v1/pedidos/**

eureka:
  cliente:
    register-with-eureka: false
    fetch-registry: false