spring:
  application:
    name: msvc-pedido
  config:
    import: 'optional:configserver:http://localhost:8888'
    
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html


